image: node:6

cache:
  paths:
  - node_modules/

env-info: 
  script: 
    - node -v
    - npm -v
build:
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - dist

pages:
  state: deploy
  image: node:6
  artifacts:
    paths:
      - dist
  only:
    - master