image: node:6

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm test

pages:
  stage: deploy
  image: node:6
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - dist
  only:
    - master