image: node:6

cache:
  paths:
  - node_modules/

build:
  script:
    - node -v
    - npm -v
    - npm install
    - npm test
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  image: node:6
  artifacts:
    paths:
      - dist
  only:
    - master
