image: node:6

cache:
  paths:
  - node_modules/

build:
  script:
   - npm install
   - npm test

pages:
  image: node:6
  dependencies:
    - build
  artifacts:
    paths:
      - dist
  only:
    - master