language: node_js
sudo: false
node_js:
  - 5
cache:
  directories:
    - node_modules
env:
  global:
    - 'NPM_CONFIG_PROGRESS="false"'
    - secure: WRua+EG9rXli/Qa58mC0Hp13a63cfFcl3LXB8okQcfwNcH4yeaLTKyQfXNl6ltr+bly7yBCWv6UASrwfRck/hvBfDZEU1Nn+MuLJD2SpvIuVG+hPJZhuBCPXp9y21ZlWGyJQ964Sqfl6HIgThp2WAv9dz1rt4R3pTJgY2acXNahpYAS3/VXXQXSEuBfOlwreuVVEZMJitILEI2rsHqFHeH0RTUuMPvSHF4nYsERh5UtKdrUxvLC8M4EWci48RbnJkR5nBNQWJkwSa4aQwYwwJawaYFHaLiKaphZumZFQYcp00FBNL3eCoWGQ7atBOPSg1VJqFaxi2rlRa4fio0yO8iSD05ZaH8jthrzwjjtKU+ilexLnekSc+AP7Ib/0O/idpCM2LIXHDeGeWjlqpjcxhjpF9n6tgH7O3Ae1wqk0G56eErAKUSs9qG2Bjr7232ea6AxkBVIc3d651m98kAq1ZQD3spMYdRcPuIFlf1I0IKP8oX40tL/L9iXj65CFEY3DxuKs7HLz0BzmbuvK0BUiT+aDkGKffmpJOIA1ZdOXV7L1FbSdP2Q8bLbkKzAoeCAK2DUBDRNyIz+Uu6Fp4QNgBBaZB9BFI7PWOk+Z/rZM1O9txbHw60uFCiwZlHg9vc28o34zmDJ4TwxnGwoGx82s4hkP6gOE8mpJWEQlYoeTSdQ=
before_install:
  - npm prune
before_deploy:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  'on':
    branch: master
    node: '5'
